Feature/check calendar dict
SmartcitySantiagoChile/inputValidator pull request #4
Opened 2021-09-22 15:02 UTC by Bastianleaf

Se agrega reglas de diccionario de calendario a **configuration.json**. Para esto se agregan los siguientes validadores:
- **CompareValueValidator**: validador que compara valores de dos columnas distintas bajo una regla. Se agregan las reglas:
   - Comparar que un año se encuentre en una fecha en formato _YYYY-MM-DD_.
   - Comparar que un mes se encuentre en una fecha en formato _YYYY-MM-DD_.
   - Comparar que un día (en formato nombre en mayúscula) sea el mismo día que una fecha en formato _YYYY-MM-DD_.
- **DateConsistencyValidator**: validador que revisa que para una columna con valores en formato _YYYY-MM-DD_ no existan fechas faltantes en todo el archivo.
- **CompleteYearFileConsistencyValidator**: validador que para la fecha del PO revisa la existencia del año completo restante.

Además se agrega un decorator **check_not_valid_col_indexes** que revisa la existencia de las columnas a revisar por los validadores. Esto evita la ejecución del validador antes de que ocurra un error de índice no válido, generando el error respectivo de no existencia de validador.

Finalmente se agrega el nombre de archivo como argumento a los validadores de tipo FILE. Esto permite que _CompleteYearFileConsistencyValidator_ tenga la fecha de PO para hacer su validación

2021-09-28 04:04 UTC, felipinbombin requested changes
hay que corregir la anidación y al correr los tests en windows fallan 5.

![image](https://user-images.githubusercontent.com/2617940/135021344-4e475f00-bff1-49bd-ad5c-0d4251794c6e.png)

![image](https://user-images.githubusercontent.com/2617940/135021362-6aa1eafb-afaf-42fb-b14d-3a2a459d76df.png)

![image](https://user-images.githubusercontent.com/2617940/135021374-4ffb326f-81d4-4ddf-9980-b155d74c2cb1.png)

![image](https://user-images.githubusercontent.com/2617940/135021395-0c93ef28-3946-4bc9-b7ce-1e7231369f3c.png)

![image](https://user-images.githubusercontent.com/2617940/135021422-6c90b288-ac30-493d-adb8-5487eb73aa7b.png)

2021-09-28 04:04 UTC, felipinbombin commented on input/configuration.json
> +            "name": "Diccionario"
¿por qué está anidado en una carpeta Diccionario? pienso que no aplica esta carpeta

2021-09-30 18:39 UTC, Bastianleaf commented on input/configuration.json
> +            "name": "Diccionario"
Efectivamente, es un error.

2021-09-30 19:27 UTC, felipinbombin approved these changes

2021-09-30 19:27 UTC, merged